name: pmlunits

channels:
  - pytorch
  - pytorch-test
  - nvidia
  - defaults
  - conda-forge
  - gpytorch
  - HuggingFace
  - fastchan
  - intel
  - nlesc
  - ivanyashchuk

dependencies:
  - python>=3.10

  - blas=*.*=mkl

  - cuda-cudart
  - cuda-cudart-dev
  - cuda-libraries
  - cuda-libraries-dev
  - cuda-nvcc
  - cuda-runtime
  - cudatoolkit
  - cudnn
  - libcusparse
  - libcusparse-dev
  - nccl

  - binutils_impl_linux-64
  - binutils_linux-64
  - gcc_impl_linux-64
  - gcc_linux-64
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - gxx_impl_linux-64
  - gxx_linux-64
  - ld_impl_linux-64
  - libgcc-devel_linux-64
  - libstdcxx-devel_linux-64
  - llvmlite
  - sysroot_linux-64

  - git>=2.34.1
  - jpeg
  - libpng>=1.6.37

  - conda>=22.9
  - importlib_metadata>=4.11.3
  - pep517>=0.12
  - pip-tools>=6.6
  - pip>=22.2
  - setuptools>=65.5
  - wheel>=0.37.1

  - dataclasses>=0.8
  - regex>=2022.7
  - rich>=12.5
  - tqdm>=4.64.1

  - joblib>=1.1
  - multiprocess>=0.70.12.2
  - threadpoolctl>=2.2

  - cython>=0.29.32
  - matplotlib>=3.5.3
  - numpy-base>=1.23.3
  - numpy>=1.23.3
  - pandas>=1.4.4
  - scikit-learn>=1.1.3
  - scipy>=1.8.1
  - seaborn>=0.12
  - statsmodels>=0.13.2

  - ipyparallel
  - ipython
  - ipywidgets
  - jupyter

  - pytorch-cuda=11.7
  - pytorch-mutex=*.*=cuda
  - pytorch>=1.13.1
  - torchvision>=0.14.1

  - gpytorch>=1.9
  - linear_operator>=0.1.1
  - pyro-api>=0.1.2
  - pyro-ppl>=1.8.2

  - libjpeg-turbo>=2.1.4
  - pillow>=9.2

  - pip:
    - tyxe>=0.0.2
